### ISSUE TITLE
Make allowHigherVersions an official option

### ISSUE THREAD

**Issue by manuelbieh** [browserslist/browserslist-useragent#10]
Hi,

first of all: great library. Thanks!

I'd love to see `allowHigherVersions` becoming an official option, without that underscore prefix and mentioned in the official list of supported options. Why? Well, I'm currently working on an app which installs a fresh version of this library and its dependencies on each deployment. Deployment is usually at least once a week but might be way less frequent in the future.

So since we dont want to show our users a "Sorry, you're browser is too old" message when they're using a browser from the future which is not even in the unreleased versions list we've set `_allowHigherVersions` to `true`. Somehow it does not feel very good, knowing that we're using a officially unstable option.

I've had a look at the code and at the tests to make sure we're not doing something crazy here and the code looks good for me. I see no reason why it is only _lightly tested_. Since all big browsers are using Semver and you're using `semver.gte` to check for the browser version I don't really see a reason why this should not be a stable, official option.

Can you elaborate a bit why you think the option is not tested well enough to be marked as stable? Maybe I can offer some help here to make it a stable, official option 🙂

**Comment by GabrielDelepine** [comment]
I totally agree with @manuelbieh 

In addition, I think the default value of `_allowHigherVersions` must be `true`

At least explaining more clearly that any unknown browser will don't match in the README.md

It could be good to provide a link to the current list of known browser

**Comment by pastelsky** [comment]
The way it works right now is, even if you have a query like `< Firefox 45`, enabling `_allowHigherVersions` would return a true match, even for browsers higher than Firefox 45. Hence, it is an opt-in flag.
