### ISSUE TITLE
matchesUA doesn't work for "Firefox > x"

### ISSUE THREAD

**Issue by prottneryara** [browserslist/browserslist-useragent#21]
My `navigator.userAgent`: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0`
Usage of `matchesUA`: `matchesUA(navigator.userAgent, { browsers: ['Firefox > 35'] })`
Expected return value: `true`
Experienced return value: `false`

**Comment by prottneryara** [comment]
However, asking for the specific version *does* work: `matchesUA(navigator.userAgent, { browsers: ['Firefox 61'] })` correctly returns true.

**Comment by pastelsky** [comment]
Please read this - https://github.com/browserslist/browserslist-useragent#when-querying-for-modern-browsers

**Comment by prottneryara** [comment]
You are suggesting to set `_allowHigherVersions` to `true`, even though the documentation warns:
>Use this with care though, since it's a wildcard, and only lightly tested.
?

**Comment by pastelsky** [comment]
Yes. Either this, or you need to wait for `browserslist-useragent` to be
updated with an updated list of all browsers that have been released.

**Comment by prottneryara** [comment]
ok, thanks
