### ISSUE TITLE
Support FB messenger's "Orca"

### ISSUE THREAD

**Issue by jaydenseric** [browserslist/browserslist-useragent#25]
A lot of people view links through the FB messenger in-app browser on Android. It has a user agent string like this:

```
Mozilla/5.0 (Linux; Android 8.0.0; LG-H930 Build/OPR1.170623.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/189.0.0.27.99;]
```

Using [whatismybrowser.com](https://developers.whatismybrowser.com/useragents/parse/#parse-useragent) to parse it:

<img width="933" alt="screen shot 2018-10-31 at 6 07 31 pm" src="https://user-images.githubusercontent.com/1754873/47772167-e5053c00-dd39-11e8-940b-34303aebfa7e.png">

I'm using `browserslist-useragent` to show out of date browser warnings on https://enamor.app with this browserslist query:

```
> 1%, node 10, not ie <= 11
```

Interestingly, this:

```js
matchesUA(
  'Mozilla/5.0 (Linux; Android 8.0.0; LG-H930 Build/OPR1.170623.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/189.0.0.27.99;]',
  {
    allowHigherVersions: true
  }
)
```

Results in `false`, but this:

```js
matchesUA(
  'Mozilla/5.0 (Linux; Android 8.0.0; LG-H930 Build/OPR1.170623.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/189.0.0.27.99;]'
)
```

Results in an error:

```
TypeError: Cannot read property 'env' of undefined
    at matchesUA (/Users/jaydenseric/Sites/enamor-app/node_modules/browserslist-u
seragent/lib/index.js:186:15)
```

**Comment by pastelsky** [comment]
I've added support for Facebook Webview (resolves to either Chrome or Safari in `3.0.2`. Let me know if you find any issues :)
