### ISSUE TITLE
Requires yamlparser but yamlparser is not a dependency in package.json

### ISSUE THREAD

**Issue by kb-coder** [browserslist/browserslist-useragent#30]
Since yamlparser is required by useragent to be able to run browserslist-useragent, can you add yamlparser as a dependency or peer dependency to your package.json?

**Comment by jackkinsella** [comment]
This issue is not with browserslist-useragent but rather with one of its dependencies, useragent: https://github.com/3rd-Eden/useragent/issues/129

**Comment by jackkinsella** [comment]
More generally, if you follow the comments, it suggests that you'll be putting a 200kb regex into your client-side JS, which could induce major slowdown. Personally I've opted for a short function just detecting the main browser causing issues (ie 10 and under)

**Comment by carpben** [comment]
I think this package is quite needed, but it is currently broken due to this bug. 
Currently this package doesn't work out of the box, and considering @jackkinsella post, not sure how to solve it. 
I'd be happy to hear from Browserslist admins and contributors on this matter.

**Comment by pastelsky** [comment]
So would it be enough if I add `yamlparser` as a dependency here? Is `request` not needed?

**Comment by kb-coder** [comment]
We ended up forking it and updating dependencies on our own. So it's not needed for us, but other might need it.
