### ISSUE TITLE
Safari iOS 12.2 not matched with "last 2 major ios_saf versions"

### ISSUE THREAD

**Issue by avrelaun** [browserslist/browserslist-useragent#40]
Hi, I'm using browserlist-useragent to detect old browser and show a message to our webapp users recommending them to change or update their browser.

Here is the supported browsers query, if not matched it triggers the message: 
				'last 2 and_chr versions',
				'last 2 and_ff versions',
				'last 2 android versions',
				'last 2 edge versions',
				'Firefox ESR',
				'last 2 ios_saf major versions',
				'last 2 safari major versions',
				'unreleased versions'

The iOS safari 12.2 should match against this query but do not, the 12.1 does match though.
Here's the useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1

Now I have two questions:
- Why is that ?
- Is this a regular thing each time a browser version is updated ? If so, I cannot rely on the tool for our use case, unless I revert completely the logic by blacklisting browsers instead of whitelisting...

**Comment by dangreen** [comment]
@avrelaun  did you try allowHigherVersions option?

**Comment by avrelaun** [comment]
Yes forgot to close that thread. Works with that option.
