### ISSUE TITLE
Edge bug

### ISSUE THREAD

**Issue by gittrolo** [browserslist/browserslist-useragent#43]
matchesUA('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362', { browsers: ['Edge >= 11']})

This code return FALSE. Why?

**Comment by pastelsky** [comment]
You need to set the `ignoreMinor` flag here. Browserslist does not store minor version numbers for all browsers, and the latest version of Edge it understands is `18`. The version you're querying for is `18.18362` which isn't present in the caniuse database. 

As noted in the README, for targeting modern browsers that browserslist does not yet support, you should enable the `allowHigherVersions` flag.

It sucks that this is so unintuitive, but hopefully, we can change this in the next major version.

**Comment by gittrolo** [comment]
Thanks
