### ISSUE TITLE
Edge 18 not recognized

### ISSUE THREAD

**Issue by kees-tce** [browserslist/browserslist-useragent#45]
Hi there,

Not really sure if this is a bug or if I'm doing something wrong, but my test Edge 18 browser is not being recognised it seems? 
This is the user agent string and browserslist I'm passing and it returns false:

`matchesUA(
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763', { browsers: [ 'and_qq 1.2',   'and_uc 12.12', 'android 76',   'baidu 7.12',  'bb 10',  'bb 7', 'chrome 79',  'chrome 78',  'edge 18',      'edge 17',  'firefox 72',   'firefox 71']})`

Versions:
browserslist-useragent 3.0.2
browserslist 4.8.5

**Comment by pastelsky** [comment]
@kees-tce Specifying `edge 18` in the browserslist is only going to match Edge `18.0.x`. 

If you want to match all Edge `18.x.x` you can set the `ignoreMinor` option to `false`.
