### ISSUE TITLE
yamlparser dependency error

### ISSUE THREAD

**Issue by konnetrofast13** [browserslist/browserslist-useragent#51]
version : 3.0.3 , 3.0.2 , 2.0.1 and maybe other releases .

while requiring thr browserslist-useragent in a CRA, i got the error : 

 Can't resolve 'yamlparser' in Path/node_modules/useragent/lib'

**Comment by NorfeldtAbtion** [comment]
had the same issue and `yarn add ymlparser` made it work, but it should be part of the dependencies.

**Comment by budarin** [comment]
have the same error, but `yarn add ymlparser` raises an error:

```yarn add ymlparser                                                     
yarn add v1.22.5
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/ymlparser: Not found".
info If you think this is a bug, please open a bug report with the information provided in ".../yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.```

**Comment by budarin** [comment]
> had the same issue and `yarn add ymlparser` made it work, but it should be part of the dependencies.

have the same error, but `yarn add ymlparser` raises an error:

```yarn add ymlparser                                                     
yarn add v1.22.5
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/ymlparser: Not found".
info If you think this is a bug, please open a bug report with the information provided in ".../yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.```

**Comment by larspa** [comment]
> > had the same issue and `yarn add ymlparser` made it work, but it should be part of the dependencies.
> 
> have the same error, but `yarn add ymlparser` raises an error:
> 
> ```
> yarn add v1.22.5
> [1/5] 🔍  Validating package.json...
> [2/5] 🔍  Resolving packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/ymlparser: Not found".
> info If you think this is a bug, please open a bug report with the information provided in ".../yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.```
> ```

Try `yarn add yamlparser` instead

**Comment by pastelsky** [comment]
This should no longer be an issue with v4.0.0 now that we're removed `useragent`
