### ISSUE TITLE
Add ChangeLog

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist-useragent#7]
Hi. I want to write about browserslist-useragent 1.1 release in `@browserslist` twitter account but didn’t find what was changed.

ChangeLog file will be very useful for project users. Here is more reasons why ChangeLog is so important for open source projects: http://keepachangelog.com/

For example, ChangeLog is mandatory for all PostCSS projects: https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md

**Comment by ai** [comment]
@pastelsky I just need a changes for 1.1. You can miss other changes.

**Comment by ai** [comment]
Do you need PR for this?

**Comment by pastelsky** [comment]
Done.
